### ISSUE TITLE
5.2.1 Config Warning

### ISSUE THREAD

**Issue by kisaku11** [ElgSoft/ElgEditorScripting#12]
while using the config file nodes, I get this warning in UE 5.2.1:

`LogConfig: Warning: GConfig::Find attempting to access config with non-normalized path ../../../../ElgEditorScripting-UE5.2/Config//ElgEditorScripting.ini. Please use FConfigCacheIni::NormalizeConfigIniPath before accessing INI files through ConfigCache.`

**Comment by ElgSoft** [comment]
It should be fixed now.
