### ISSUE TITLE
SlowTask is not showing anymore

### ISSUE THREAD

**Issue by MarobaDev** [ElgSoft/ElgEditorScripting#9]
I noticed since converting projects to UE5, the SlowTask progressbar will not show up anymore.
Also happens in a clean empty fork of ElgEditorScripting.

This would easily be reproducable:
Run the "EW_ToolbarButton_SlowTask" and press the "SlowTask" Button

Does somebody have a clue? Great function rich repo btw. :)

**Comment by ElgSoft** [comment]
Fixed so SlowTask should now work in UE5

**Comment by ElgSoft** [comment]
Fixed so SlowTask should now work in UE5

**Comment by ElgSoft** [comment]
Fixed so SlowTask should now work in UE5

**Comment by MarobaDev** [comment]
Thank you. Works like a charm.
